using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Oasis.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace Oasis.Data
{
    public class DataContext:IdentityDbContext<UserTable>
    {
        public DataContext()
        {
            
        }

        public DataContext(DbContextOptions options) :base(options)
        {
            
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //base.OnConfiguring(optionsBuilder);

            optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=OasisDB;Integrated Security=True;TrustServerCertificate=true;");
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            // Give a default value to Completed Column
            builder.Entity<ToDo>()
                .Property(x => x.Completed)
                .HasDefaultValue(false);

            //Make UserId AutoGenerated

              builder.Entity<UserTable>()
               .Property(u => u.UserId)
               .ValueGeneratedOnAdd();
        }

        public  DbSet<ToDo> ToDos { get; set; }
    }
}
